### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by heyitscassio** [godeezer/lib#5]
Hello! Pretty nice project, but I think there is a need for some documentation. A example in the readme would be pretty nice, so newcomers like me could start something, and will make it easier to other people to contribute with code and more documentation.

**Comment by samhza** [comment]
Hey, thanks for opening this issue, the readme was quite lacking. I've added a few examples to the readme now in 13790d33f2d36c9b05773dfab22b0518ec2dc9bf, if you'd like to add more examples/make changes feel free to open a pull request.
